# Generated by Django 5.1.2 on 2025-01-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='user',
        ),
    ]
