# Generated by Django 5.1.5 on 2025-01-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_alter_bot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
    ]
