# Generated by Django 5.1.5 on 2025-01-19 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_bot_total_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='TestBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='bots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wins', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('chips_won', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
