# Generated by Django 5.1.5 on 2025-01-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_bot_path_testbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
