# Generated by Django 5.1.5 on 2025-01-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0007_alter_bot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
